version: '3.4'

services:
  shopping.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shopping.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  shopping.db:
    container_name: shoppingdb
    restart: always
    ports:
      - "27017:2701"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
